/buzzer_controller:
  ros__parameters:
    pin: 5
/motor_controller:
  ros__parameters:
    pins: [17, 27, 22, 18]
    esc_max: 2000
    esc_min: 1000
/imu_controller:
  ros__parameters:
    freq: 75
/gps_controller:
  ros__parameters:
    baud: 115200
    freq: 10.0
/ping_controller:
  ros__parameters:
    echo_pin: 6
    trig_pin: 19
    freq: 20.0
/failsafe:
  ros__parameters:
    esc_min: 1000
    pins: [17, 27, 22, 18]
/**:
  ros__parameters:
    debug: true
